site_name: Still.js Framework
site_url: https://stilljs.dev
nav:
  - WHAT IS Still.js: index.md
  - INSTALLATION:
      - Setup OPTION 1 - Still.js Project: installation-and-running.md
      - Setup OPTION 2 - Using CDN: installation-and-running-cdn.md
      - Integration with React (Microfrontend): integration-with-react.md
  - VS Code Setup Considerations: basic-vs-code-setup.md
  - STILL CLI: still-cli.md
  - GET STARTED: get-start.md
  - COMPONENTS:
      - Fundamentls: components.md
      - Inter Communication: components-communication.md
      - Lone component and Microfrontend: lone-component.md
      - Private Components: components-private.md
      - Multi level (3+) nesting: components-nesting-3+.md
  - COMPONENT ANNOTATIONS: annotation.md
  - TEMPLATE DIRECTIVE: directive.md
  - CONDITIONAL RENDERING, SHOW/HIDE: conditional-rendering.md
  - ROUTING & NAVIGATION: routing.md
  - LIFECYCLE HOOKS: lifecycle-hooks.md
  - APP TEMPLATE: app-template.md
  - TYPE & TYPE HINTING: typing-and-typ-hinting.md
  - STRUCTURE: architecture.md
  #- Playground: playground.md
theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo-no-bg.ico
  features:
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - content.tooltips

  icon:
    repo: fontawesome/brands/github
  palette:
    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep orange

    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: deep purple

extra_css:
  - assets/css/general.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/codemirror.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/theme/dracula.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/codemirror.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/mode/javascript/javascript.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.13/addon/edit/closebrackets.min.js
  - docs/assets/editor.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg #Diagrams settings


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Tab diagrams
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fUVJRTmQ9f
      name: Stilljs Discord Channel
    - icon: fontawesome/brands/github
      link: https://github.com/still-js/core
      name: Stilljs Git repository

copyright: Cpyright &copy; 2025 StillJS
